version: "3.7"

services:
  consul:
    container_name: consul
    image: consul
    command: "agent -dev -client 0.0.0.0"
    ports:
      - "8300:8300"
      - "8500:8500"
  distributed-logger:
    build: 
        context: .
        dockerfile: ./node/Dockerfile
    depends_on:
      - consul
  producer:
    build:   
        context: .
        dockerfile: ./producer/Dockerfile
    depends_on:
      - distributed-logger